// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rmintreward/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryActLatestCycleRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryActLatestCycleRequest) Reset()         { *m = QueryActLatestCycleRequest{} }
func (m *QueryActLatestCycleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryActLatestCycleRequest) ProtoMessage()    {}
func (*QueryActLatestCycleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{2}
}
func (m *QueryActLatestCycleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActLatestCycleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActLatestCycleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActLatestCycleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActLatestCycleRequest.Merge(m, src)
}
func (m *QueryActLatestCycleRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActLatestCycleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActLatestCycleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActLatestCycleRequest proto.InternalMessageInfo

func (m *QueryActLatestCycleRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryActLatestCycleResponse struct {
	LatestCycle uint64 `protobuf:"varint,1,opt,name=latestCycle,proto3" json:"latestCycle,omitempty"`
}

func (m *QueryActLatestCycleResponse) Reset()         { *m = QueryActLatestCycleResponse{} }
func (m *QueryActLatestCycleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryActLatestCycleResponse) ProtoMessage()    {}
func (*QueryActLatestCycleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{3}
}
func (m *QueryActLatestCycleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActLatestCycleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActLatestCycleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActLatestCycleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActLatestCycleResponse.Merge(m, src)
}
func (m *QueryActLatestCycleResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActLatestCycleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActLatestCycleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActLatestCycleResponse proto.InternalMessageInfo

func (m *QueryActLatestCycleResponse) GetLatestCycle() uint64 {
	if m != nil {
		return m.LatestCycle
	}
	return 0
}

type QueryActDetailRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Cycle uint64 `protobuf:"varint,2,opt,name=cycle,proto3" json:"cycle,omitempty"`
}

func (m *QueryActDetailRequest) Reset()         { *m = QueryActDetailRequest{} }
func (m *QueryActDetailRequest) String() string { return proto.CompactTextString(m) }
func (*QueryActDetailRequest) ProtoMessage()    {}
func (*QueryActDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{4}
}
func (m *QueryActDetailRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActDetailRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActDetailRequest.Merge(m, src)
}
func (m *QueryActDetailRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActDetailRequest proto.InternalMessageInfo

func (m *QueryActDetailRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryActDetailRequest) GetCycle() uint64 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

type QueryActDetailResponse struct {
	Act *MintRewardAct `protobuf:"bytes,4,opt,name=act,proto3" json:"act,omitempty"`
}

func (m *QueryActDetailResponse) Reset()         { *m = QueryActDetailResponse{} }
func (m *QueryActDetailResponse) String() string { return proto.CompactTextString(m) }
func (*QueryActDetailResponse) ProtoMessage()    {}
func (*QueryActDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{5}
}
func (m *QueryActDetailResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActDetailResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActDetailResponse.Merge(m, src)
}
func (m *QueryActDetailResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActDetailResponse proto.InternalMessageInfo

func (m *QueryActDetailResponse) GetAct() *MintRewardAct {
	if m != nil {
		return m.Act
	}
	return nil
}

type QueryUserMintCountRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Cycle   uint64 `protobuf:"varint,3,opt,name=cycle,proto3" json:"cycle,omitempty"`
}

func (m *QueryUserMintCountRequest) Reset()         { *m = QueryUserMintCountRequest{} }
func (m *QueryUserMintCountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserMintCountRequest) ProtoMessage()    {}
func (*QueryUserMintCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{6}
}
func (m *QueryUserMintCountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserMintCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserMintCountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserMintCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserMintCountRequest.Merge(m, src)
}
func (m *QueryUserMintCountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserMintCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserMintCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserMintCountRequest proto.InternalMessageInfo

func (m *QueryUserMintCountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryUserMintCountRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryUserMintCountRequest) GetCycle() uint64 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

type QueryUserMintCountResponse struct {
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryUserMintCountResponse) Reset()         { *m = QueryUserMintCountResponse{} }
func (m *QueryUserMintCountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserMintCountResponse) ProtoMessage()    {}
func (*QueryUserMintCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{7}
}
func (m *QueryUserMintCountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserMintCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserMintCountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserMintCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserMintCountResponse.Merge(m, src)
}
func (m *QueryUserMintCountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserMintCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserMintCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserMintCountResponse proto.InternalMessageInfo

func (m *QueryUserMintCountResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type QueryUserActsRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryUserActsRequest) Reset()         { *m = QueryUserActsRequest{} }
func (m *QueryUserActsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserActsRequest) ProtoMessage()    {}
func (*QueryUserActsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{8}
}
func (m *QueryUserActsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserActsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserActsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserActsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserActsRequest.Merge(m, src)
}
func (m *QueryUserActsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserActsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserActsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserActsRequest proto.InternalMessageInfo

func (m *QueryUserActsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryUserActsRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryUserActsResponse struct {
	Acts *Acts `protobuf:"bytes,1,opt,name=acts,proto3" json:"acts,omitempty"`
}

func (m *QueryUserActsResponse) Reset()         { *m = QueryUserActsResponse{} }
func (m *QueryUserActsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserActsResponse) ProtoMessage()    {}
func (*QueryUserActsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a060f1414d4add49, []int{9}
}
func (m *QueryUserActsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserActsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserActsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserActsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserActsResponse.Merge(m, src)
}
func (m *QueryUserActsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserActsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserActsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserActsResponse proto.InternalMessageInfo

func (m *QueryUserActsResponse) GetActs() *Acts {
	if m != nil {
		return m.Acts
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "stafihub.stafihub.rmintreward.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "stafihub.stafihub.rmintreward.QueryParamsResponse")
	proto.RegisterType((*QueryActLatestCycleRequest)(nil), "stafihub.stafihub.rmintreward.QueryActLatestCycleRequest")
	proto.RegisterType((*QueryActLatestCycleResponse)(nil), "stafihub.stafihub.rmintreward.QueryActLatestCycleResponse")
	proto.RegisterType((*QueryActDetailRequest)(nil), "stafihub.stafihub.rmintreward.QueryActDetailRequest")
	proto.RegisterType((*QueryActDetailResponse)(nil), "stafihub.stafihub.rmintreward.QueryActDetailResponse")
	proto.RegisterType((*QueryUserMintCountRequest)(nil), "stafihub.stafihub.rmintreward.QueryUserMintCountRequest")
	proto.RegisterType((*QueryUserMintCountResponse)(nil), "stafihub.stafihub.rmintreward.QueryUserMintCountResponse")
	proto.RegisterType((*QueryUserActsRequest)(nil), "stafihub.stafihub.rmintreward.QueryUserActsRequest")
	proto.RegisterType((*QueryUserActsResponse)(nil), "stafihub.stafihub.rmintreward.QueryUserActsResponse")
}

func init() { proto.RegisterFile("rmintreward/query.proto", fileDescriptor_a060f1414d4add49) }

var fileDescriptor_a060f1414d4add49 = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5f, 0x6b, 0x13, 0x4f,
	0x14, 0xcd, 0xb6, 0x69, 0xfb, 0xeb, 0x94, 0x9f, 0x0f, 0x63, 0xd4, 0xb8, 0xea, 0x5a, 0x56, 0x8a,
	0x22, 0x9a, 0xb5, 0x69, 0xa5, 0xa6, 0x8a, 0x25, 0x8d, 0x88, 0x14, 0x85, 0xba, 0x20, 0x48, 0x5f,
	0xc2, 0x64, 0x77, 0x5c, 0x17, 0xb2, 0x3b, 0xdb, 0x9d, 0x89, 0x5a, 0x4a, 0x5e, 0xfc, 0x04, 0x82,
	0xef, 0x7e, 0x0f, 0xf1, 0x5d, 0xf2, 0x58, 0x10, 0xc4, 0x27, 0x91, 0xc4, 0x0f, 0x22, 0x7b, 0x77,
	0x36, 0x7f, 0x9a, 0xa5, 0xd9, 0xe4, 0x6d, 0xe6, 0xce, 0x3d, 0xe7, 0x9e, 0x73, 0xf7, 0x5e, 0x16,
	0x5d, 0x0a, 0x3d, 0xd7, 0x17, 0x21, 0x7d, 0x4f, 0x42, 0xdb, 0x38, 0x6c, 0xd1, 0xf0, 0xa8, 0x14,
	0x84, 0x4c, 0x30, 0x7c, 0x8d, 0x0b, 0xf2, 0xc6, 0x7d, 0xdb, 0x6a, 0x94, 0xfa, 0x87, 0xa1, 0x54,
	0xb5, 0xe0, 0x30, 0x87, 0x41, 0xa6, 0x11, 0x9d, 0x62, 0x90, 0x7a, 0xd5, 0x61, 0xcc, 0x69, 0x52,
	0x83, 0x04, 0xae, 0x41, 0x7c, 0x9f, 0x09, 0x22, 0x5c, 0xe6, 0x73, 0xf9, 0x7a, 0xdb, 0x62, 0xdc,
	0x63, 0xdc, 0x68, 0x10, 0x4e, 0xe3, 0x5a, 0xc6, 0xbb, 0xf5, 0x06, 0x15, 0x64, 0xdd, 0x08, 0x88,
	0xe3, 0xfa, 0x90, 0x2c, 0x73, 0x8b, 0xc3, 0xba, 0x02, 0x12, 0x12, 0x8f, 0xa7, 0xbd, 0x78, 0xcc,
	0xa6, 0x4d, 0xf9, 0xa2, 0x17, 0x10, 0x7e, 0x19, 0xb1, 0xee, 0x43, 0xba, 0x49, 0x0f, 0x5b, 0x94,
	0x0b, 0xfd, 0x00, 0x9d, 0x1f, 0x89, 0xf2, 0x80, 0xf9, 0x9c, 0xe2, 0x1a, 0x5a, 0x8c, 0x69, 0x8b,
	0xca, 0xaa, 0x72, 0x6b, 0xa5, 0xbc, 0x56, 0x3a, 0xd3, 0x70, 0x29, 0x86, 0xef, 0xe6, 0x3b, 0xbf,
	0xaf, 0xe7, 0x4c, 0x09, 0xd5, 0xcb, 0x48, 0x05, 0xee, 0xaa, 0x25, 0x9e, 0x13, 0x41, 0xb9, 0xa8,
	0x1d, 0x59, 0x4d, 0x2a, 0x2b, 0xe3, 0x02, 0x5a, 0xb0, 0xa9, 0xcf, 0x3c, 0xa8, 0xb0, 0x6c, 0xc6,
	0x17, 0x7d, 0x07, 0x5d, 0x49, 0xc5, 0x48, 0x5d, 0xab, 0x68, 0xa5, 0x39, 0x08, 0x03, 0x34, 0x6f,
	0x0e, 0x87, 0xf4, 0x1a, 0xba, 0x90, 0x10, 0x3c, 0xa1, 0x82, 0xb8, 0xcd, 0x33, 0xeb, 0x45, 0x51,
	0x0b, 0xa8, 0xe6, 0x80, 0x2a, 0xbe, 0xe8, 0xaf, 0xd1, 0xc5, 0xd3, 0x24, 0x52, 0xc0, 0x63, 0x34,
	0x4f, 0x2c, 0x51, 0xcc, 0x43, 0x57, 0xee, 0x4c, 0xe8, 0xca, 0x0b, 0xd7, 0x17, 0x26, 0x1c, 0xab,
	0x96, 0x30, 0x23, 0xa0, 0x4e, 0xd0, 0x65, 0x60, 0x7e, 0xc5, 0x69, 0x18, 0x3d, 0xd7, 0x58, 0x2b,
	0xca, 0x89, 0x25, 0x16, 0xd1, 0x12, 0xb1, 0xed, 0x90, 0x72, 0x2e, 0x45, 0x26, 0xd7, 0x81, 0xf8,
	0xb9, 0x54, 0xf1, 0xf3, 0xc3, 0xe2, 0x93, 0xb6, 0x9f, 0x2a, 0x21, 0x0d, 0x44, 0x98, 0x28, 0x20,
	0x7b, 0x17, 0x5f, 0xf4, 0xa7, 0xa8, 0xd0, 0xc7, 0x54, 0x2d, 0xc1, 0x67, 0x54, 0xa4, 0xef, 0xcb,
	0xee, 0x0f, 0x78, 0x64, 0xd9, 0x2d, 0x94, 0x27, 0x96, 0x48, 0xc6, 0xe9, 0xc6, 0x84, 0xc6, 0x01,
	0x14, 0x00, 0xe5, 0xef, 0x4b, 0x68, 0x01, 0x28, 0xf1, 0x17, 0x05, 0x2d, 0xc6, 0x73, 0x86, 0xd7,
	0x27, 0xe0, 0xc7, 0x07, 0x5d, 0x2d, 0x4f, 0x03, 0x89, 0x45, 0xeb, 0x77, 0x3f, 0xfe, 0xf8, 0xfb,
	0x79, 0xee, 0x26, 0x5e, 0x33, 0x12, 0xc8, 0xe0, 0x30, 0xbe, 0x81, 0xb8, 0xa3, 0xa0, 0x73, 0xa3,
	0x73, 0x8b, 0x2b, 0x59, 0xaa, 0xa6, 0xee, 0x87, 0xba, 0x3d, 0x0b, 0x54, 0x0a, 0xdf, 0x01, 0xe1,
	0x15, 0xbc, 0x35, 0x41, 0x38, 0xb1, 0x44, 0x3d, 0x5e, 0x9e, 0x3a, 0xcc, 0x8e, 0x71, 0x0c, 0x9f,
	0xb1, 0x8d, 0xbf, 0x29, 0x68, 0xb9, 0x3f, 0xfc, 0x78, 0x33, 0xa3, 0x94, 0x91, 0x85, 0x53, 0xef,
	0x4f, 0x89, 0x92, 0xda, 0xab, 0xa0, 0xfd, 0x21, 0xae, 0x64, 0xd0, 0x6e, 0x03, 0x34, 0x51, 0x6d,
	0x1c, 0x83, 0x89, 0x36, 0xfe, 0xa9, 0xa0, 0xff, 0x47, 0xa6, 0x1f, 0x3f, 0xc8, 0xa2, 0x25, 0x6d,
	0x27, 0xd5, 0xca, 0x0c, 0x48, 0xe9, 0x64, 0x1f, 0x9c, 0xec, 0xe1, 0x67, 0x13, 0x9c, 0xb4, 0x38,
	0x0d, 0xeb, 0xd1, 0xbd, 0x0e, 0xcb, 0x68, 0x1c, 0xcb, 0x1d, 0x6b, 0x8f, 0x19, 0xfb, 0xaa, 0xa0,
	0xff, 0x92, 0xd5, 0xc2, 0x1b, 0x59, 0x95, 0x0d, 0x2d, 0xb4, 0xba, 0x39, 0x1d, 0x48, 0x3a, 0xd9,
	0x05, 0x27, 0x8f, 0xf0, 0x76, 0x16, 0x27, 0xd1, 0xda, 0x8e, 0x7b, 0xd8, 0xdd, 0xeb, 0x74, 0x35,
	0xe5, 0xa4, 0xab, 0x29, 0x7f, 0xba, 0x9a, 0xf2, 0xa9, 0xa7, 0xe5, 0x4e, 0x7a, 0x5a, 0xee, 0x57,
	0x4f, 0xcb, 0x1d, 0xdc, 0x73, 0x5c, 0x11, 0xe9, 0xb0, 0x98, 0x97, 0xc2, 0xff, 0x61, 0xa4, 0x82,
	0x38, 0x0a, 0x28, 0x6f, 0x2c, 0xc2, 0x2f, 0x6d, 0xe3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3a,
	0x23, 0x12, 0x72, 0xa0, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ActLatestCycle items.
	ActLatestCycle(ctx context.Context, in *QueryActLatestCycleRequest, opts ...grpc.CallOption) (*QueryActLatestCycleResponse, error)
	// Queries a list of ActDetail items.
	ActDetail(ctx context.Context, in *QueryActDetailRequest, opts ...grpc.CallOption) (*QueryActDetailResponse, error)
	// Queries a list of UserMintCount items.
	UserMintCount(ctx context.Context, in *QueryUserMintCountRequest, opts ...grpc.CallOption) (*QueryUserMintCountResponse, error)
	// Queries a list of UserActs items.
	UserActs(ctx context.Context, in *QueryUserActsRequest, opts ...grpc.CallOption) (*QueryUserActsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rmintreward.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActLatestCycle(ctx context.Context, in *QueryActLatestCycleRequest, opts ...grpc.CallOption) (*QueryActLatestCycleResponse, error) {
	out := new(QueryActLatestCycleResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rmintreward.Query/ActLatestCycle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActDetail(ctx context.Context, in *QueryActDetailRequest, opts ...grpc.CallOption) (*QueryActDetailResponse, error) {
	out := new(QueryActDetailResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rmintreward.Query/ActDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserMintCount(ctx context.Context, in *QueryUserMintCountRequest, opts ...grpc.CallOption) (*QueryUserMintCountResponse, error) {
	out := new(QueryUserMintCountResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rmintreward.Query/UserMintCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserActs(ctx context.Context, in *QueryUserActsRequest, opts ...grpc.CallOption) (*QueryUserActsResponse, error) {
	out := new(QueryUserActsResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rmintreward.Query/UserActs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ActLatestCycle items.
	ActLatestCycle(context.Context, *QueryActLatestCycleRequest) (*QueryActLatestCycleResponse, error)
	// Queries a list of ActDetail items.
	ActDetail(context.Context, *QueryActDetailRequest) (*QueryActDetailResponse, error)
	// Queries a list of UserMintCount items.
	UserMintCount(context.Context, *QueryUserMintCountRequest) (*QueryUserMintCountResponse, error)
	// Queries a list of UserActs items.
	UserActs(context.Context, *QueryUserActsRequest) (*QueryUserActsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ActLatestCycle(ctx context.Context, req *QueryActLatestCycleRequest) (*QueryActLatestCycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActLatestCycle not implemented")
}
func (*UnimplementedQueryServer) ActDetail(ctx context.Context, req *QueryActDetailRequest) (*QueryActDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActDetail not implemented")
}
func (*UnimplementedQueryServer) UserMintCount(ctx context.Context, req *QueryUserMintCountRequest) (*QueryUserMintCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMintCount not implemented")
}
func (*UnimplementedQueryServer) UserActs(ctx context.Context, req *QueryUserActsRequest) (*QueryUserActsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserActs not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rmintreward.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActLatestCycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActLatestCycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActLatestCycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rmintreward.Query/ActLatestCycle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActLatestCycle(ctx, req.(*QueryActLatestCycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rmintreward.Query/ActDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActDetail(ctx, req.(*QueryActDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserMintCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserMintCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserMintCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rmintreward.Query/UserMintCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserMintCount(ctx, req.(*QueryUserMintCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserActs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserActsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserActs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rmintreward.Query/UserActs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserActs(ctx, req.(*QueryUserActsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stafihub.stafihub.rmintreward.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ActLatestCycle",
			Handler:    _Query_ActLatestCycle_Handler,
		},
		{
			MethodName: "ActDetail",
			Handler:    _Query_ActDetail_Handler,
		},
		{
			MethodName: "UserMintCount",
			Handler:    _Query_UserMintCount_Handler,
		},
		{
			MethodName: "UserActs",
			Handler:    _Query_UserActs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rmintreward/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryActLatestCycleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActLatestCycleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActLatestCycleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryActLatestCycleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActLatestCycleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActLatestCycleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LatestCycle != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LatestCycle))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryActDetailRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActDetailRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActDetailRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cycle != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Cycle))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryActDetailResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActDetailResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActDetailResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Act != nil {
		{
			size, err := m.Act.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserMintCountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserMintCountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserMintCountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cycle != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Cycle))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserMintCountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserMintCountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserMintCountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserActsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserActsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserActsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserActsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserActsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserActsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Acts != nil {
		{
			size, err := m.Acts.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryActLatestCycleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryActLatestCycleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LatestCycle != 0 {
		n += 1 + sovQuery(uint64(m.LatestCycle))
	}
	return n
}

func (m *QueryActDetailRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Cycle != 0 {
		n += 1 + sovQuery(uint64(m.Cycle))
	}
	return n
}

func (m *QueryActDetailResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Act != nil {
		l = m.Act.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserMintCountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Cycle != 0 {
		n += 1 + sovQuery(uint64(m.Cycle))
	}
	return n
}

func (m *QueryUserMintCountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func (m *QueryUserActsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserActsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Acts != nil {
		l = m.Acts.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActLatestCycleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActLatestCycleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActLatestCycleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActLatestCycleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActLatestCycleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActLatestCycleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestCycle", wireType)
			}
			m.LatestCycle = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestCycle |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActDetailRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActDetailRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActDetailRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cycle", wireType)
			}
			m.Cycle = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cycle |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActDetailResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActDetailResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActDetailResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Act", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Act == nil {
				m.Act = &MintRewardAct{}
			}
			if err := m.Act.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserMintCountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserMintCountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserMintCountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cycle", wireType)
			}
			m.Cycle = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cycle |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserMintCountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserMintCountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserMintCountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserActsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserActsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserActsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserActsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserActsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserActsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Acts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Acts == nil {
				m.Acts = &Acts{}
			}
			if err := m.Acts.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
