// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rstaking/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetInflationBase struct {
	Creator       string                                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	InflationBase github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=inflationBase,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"inflationBase"`
}

func (m *MsgSetInflationBase) Reset()         { *m = MsgSetInflationBase{} }
func (m *MsgSetInflationBase) String() string { return proto.CompactTextString(m) }
func (*MsgSetInflationBase) ProtoMessage()    {}
func (*MsgSetInflationBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{0}
}
func (m *MsgSetInflationBase) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetInflationBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetInflationBase.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetInflationBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetInflationBase.Merge(m, src)
}
func (m *MsgSetInflationBase) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetInflationBase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetInflationBase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetInflationBase proto.InternalMessageInfo

func (m *MsgSetInflationBase) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgSetInflationBaseResponse struct {
}

func (m *MsgSetInflationBaseResponse) Reset()         { *m = MsgSetInflationBaseResponse{} }
func (m *MsgSetInflationBaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetInflationBaseResponse) ProtoMessage()    {}
func (*MsgSetInflationBaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{1}
}
func (m *MsgSetInflationBaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetInflationBaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetInflationBaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetInflationBaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetInflationBaseResponse.Merge(m, src)
}
func (m *MsgSetInflationBaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetInflationBaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetInflationBaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetInflationBaseResponse proto.InternalMessageInfo

type MsgAddValToWhitelist struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ValAddress string `protobuf:"bytes,2,opt,name=valAddress,proto3" json:"valAddress,omitempty"`
}

func (m *MsgAddValToWhitelist) Reset()         { *m = MsgAddValToWhitelist{} }
func (m *MsgAddValToWhitelist) String() string { return proto.CompactTextString(m) }
func (*MsgAddValToWhitelist) ProtoMessage()    {}
func (*MsgAddValToWhitelist) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{2}
}
func (m *MsgAddValToWhitelist) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddValToWhitelist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddValToWhitelist.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddValToWhitelist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddValToWhitelist.Merge(m, src)
}
func (m *MsgAddValToWhitelist) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddValToWhitelist) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddValToWhitelist.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddValToWhitelist proto.InternalMessageInfo

func (m *MsgAddValToWhitelist) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddValToWhitelist) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

type MsgAddValToWhitelistResponse struct {
}

func (m *MsgAddValToWhitelistResponse) Reset()         { *m = MsgAddValToWhitelistResponse{} }
func (m *MsgAddValToWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddValToWhitelistResponse) ProtoMessage()    {}
func (*MsgAddValToWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{3}
}
func (m *MsgAddValToWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddValToWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddValToWhitelistResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddValToWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddValToWhitelistResponse.Merge(m, src)
}
func (m *MsgAddValToWhitelistResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddValToWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddValToWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddValToWhitelistResponse proto.InternalMessageInfo

type MsgToggleValidatorWhitelistSwitch struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgToggleValidatorWhitelistSwitch) Reset()         { *m = MsgToggleValidatorWhitelistSwitch{} }
func (m *MsgToggleValidatorWhitelistSwitch) String() string { return proto.CompactTextString(m) }
func (*MsgToggleValidatorWhitelistSwitch) ProtoMessage()    {}
func (*MsgToggleValidatorWhitelistSwitch) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{4}
}
func (m *MsgToggleValidatorWhitelistSwitch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgToggleValidatorWhitelistSwitch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgToggleValidatorWhitelistSwitch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgToggleValidatorWhitelistSwitch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToggleValidatorWhitelistSwitch.Merge(m, src)
}
func (m *MsgToggleValidatorWhitelistSwitch) XXX_Size() int {
	return m.Size()
}
func (m *MsgToggleValidatorWhitelistSwitch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToggleValidatorWhitelistSwitch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToggleValidatorWhitelistSwitch proto.InternalMessageInfo

func (m *MsgToggleValidatorWhitelistSwitch) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgToggleValidatorWhitelistSwitchResponse struct {
}

func (m *MsgToggleValidatorWhitelistSwitchResponse) Reset() {
	*m = MsgToggleValidatorWhitelistSwitchResponse{}
}
func (m *MsgToggleValidatorWhitelistSwitchResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgToggleValidatorWhitelistSwitchResponse) ProtoMessage() {}
func (*MsgToggleValidatorWhitelistSwitchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{5}
}
func (m *MsgToggleValidatorWhitelistSwitchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgToggleValidatorWhitelistSwitchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgToggleValidatorWhitelistSwitchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgToggleValidatorWhitelistSwitchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToggleValidatorWhitelistSwitchResponse.Merge(m, src)
}
func (m *MsgToggleValidatorWhitelistSwitchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgToggleValidatorWhitelistSwitchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToggleValidatorWhitelistSwitchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToggleValidatorWhitelistSwitchResponse proto.InternalMessageInfo

type MsgWithdraw struct {
	Creator   string                                  `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount    github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,2,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"amount"`
	Recipient string                                  `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (m *MsgWithdraw) Reset()         { *m = MsgWithdraw{} }
func (m *MsgWithdraw) String() string { return proto.CompactTextString(m) }
func (*MsgWithdraw) ProtoMessage()    {}
func (*MsgWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{6}
}
func (m *MsgWithdraw) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdraw.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdraw.Merge(m, src)
}
func (m *MsgWithdraw) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdraw proto.InternalMessageInfo

func (m *MsgWithdraw) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgWithdraw) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

type MsgWithdrawResponse struct {
}

func (m *MsgWithdrawResponse) Reset()         { *m = MsgWithdrawResponse{} }
func (m *MsgWithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawResponse) ProtoMessage()    {}
func (*MsgWithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{7}
}
func (m *MsgWithdrawResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawResponse.Merge(m, src)
}
func (m *MsgWithdrawResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawResponse proto.InternalMessageInfo

type MsgAddDelegatorToWhitelist struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	DelAddress string `protobuf:"bytes,2,opt,name=delAddress,proto3" json:"delAddress,omitempty"`
}

func (m *MsgAddDelegatorToWhitelist) Reset()         { *m = MsgAddDelegatorToWhitelist{} }
func (m *MsgAddDelegatorToWhitelist) String() string { return proto.CompactTextString(m) }
func (*MsgAddDelegatorToWhitelist) ProtoMessage()    {}
func (*MsgAddDelegatorToWhitelist) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{8}
}
func (m *MsgAddDelegatorToWhitelist) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddDelegatorToWhitelist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddDelegatorToWhitelist.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddDelegatorToWhitelist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddDelegatorToWhitelist.Merge(m, src)
}
func (m *MsgAddDelegatorToWhitelist) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddDelegatorToWhitelist) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddDelegatorToWhitelist.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddDelegatorToWhitelist proto.InternalMessageInfo

func (m *MsgAddDelegatorToWhitelist) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddDelegatorToWhitelist) GetDelAddress() string {
	if m != nil {
		return m.DelAddress
	}
	return ""
}

type MsgAddDelegatorToWhitelistResponse struct {
}

func (m *MsgAddDelegatorToWhitelistResponse) Reset()         { *m = MsgAddDelegatorToWhitelistResponse{} }
func (m *MsgAddDelegatorToWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddDelegatorToWhitelistResponse) ProtoMessage()    {}
func (*MsgAddDelegatorToWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{9}
}
func (m *MsgAddDelegatorToWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddDelegatorToWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddDelegatorToWhitelistResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddDelegatorToWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddDelegatorToWhitelistResponse.Merge(m, src)
}
func (m *MsgAddDelegatorToWhitelistResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddDelegatorToWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddDelegatorToWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddDelegatorToWhitelistResponse proto.InternalMessageInfo

type MsgToggleDelegatorWhitelistSwitch struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgToggleDelegatorWhitelistSwitch) Reset()         { *m = MsgToggleDelegatorWhitelistSwitch{} }
func (m *MsgToggleDelegatorWhitelistSwitch) String() string { return proto.CompactTextString(m) }
func (*MsgToggleDelegatorWhitelistSwitch) ProtoMessage()    {}
func (*MsgToggleDelegatorWhitelistSwitch) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{10}
}
func (m *MsgToggleDelegatorWhitelistSwitch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgToggleDelegatorWhitelistSwitch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgToggleDelegatorWhitelistSwitch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgToggleDelegatorWhitelistSwitch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToggleDelegatorWhitelistSwitch.Merge(m, src)
}
func (m *MsgToggleDelegatorWhitelistSwitch) XXX_Size() int {
	return m.Size()
}
func (m *MsgToggleDelegatorWhitelistSwitch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToggleDelegatorWhitelistSwitch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToggleDelegatorWhitelistSwitch proto.InternalMessageInfo

func (m *MsgToggleDelegatorWhitelistSwitch) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgToggleDelegatorWhitelistSwitchResponse struct {
}

func (m *MsgToggleDelegatorWhitelistSwitchResponse) Reset() {
	*m = MsgToggleDelegatorWhitelistSwitchResponse{}
}
func (m *MsgToggleDelegatorWhitelistSwitchResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgToggleDelegatorWhitelistSwitchResponse) ProtoMessage() {}
func (*MsgToggleDelegatorWhitelistSwitchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4bfb0e643e29ba, []int{11}
}
func (m *MsgToggleDelegatorWhitelistSwitchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgToggleDelegatorWhitelistSwitchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgToggleDelegatorWhitelistSwitchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgToggleDelegatorWhitelistSwitchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToggleDelegatorWhitelistSwitchResponse.Merge(m, src)
}
func (m *MsgToggleDelegatorWhitelistSwitchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgToggleDelegatorWhitelistSwitchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToggleDelegatorWhitelistSwitchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToggleDelegatorWhitelistSwitchResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetInflationBase)(nil), "stafihub.stafihub.rstaking.MsgSetInflationBase")
	proto.RegisterType((*MsgSetInflationBaseResponse)(nil), "stafihub.stafihub.rstaking.MsgSetInflationBaseResponse")
	proto.RegisterType((*MsgAddValToWhitelist)(nil), "stafihub.stafihub.rstaking.MsgAddValToWhitelist")
	proto.RegisterType((*MsgAddValToWhitelistResponse)(nil), "stafihub.stafihub.rstaking.MsgAddValToWhitelistResponse")
	proto.RegisterType((*MsgToggleValidatorWhitelistSwitch)(nil), "stafihub.stafihub.rstaking.MsgToggleValidatorWhitelistSwitch")
	proto.RegisterType((*MsgToggleValidatorWhitelistSwitchResponse)(nil), "stafihub.stafihub.rstaking.MsgToggleValidatorWhitelistSwitchResponse")
	proto.RegisterType((*MsgWithdraw)(nil), "stafihub.stafihub.rstaking.MsgWithdraw")
	proto.RegisterType((*MsgWithdrawResponse)(nil), "stafihub.stafihub.rstaking.MsgWithdrawResponse")
	proto.RegisterType((*MsgAddDelegatorToWhitelist)(nil), "stafihub.stafihub.rstaking.MsgAddDelegatorToWhitelist")
	proto.RegisterType((*MsgAddDelegatorToWhitelistResponse)(nil), "stafihub.stafihub.rstaking.MsgAddDelegatorToWhitelistResponse")
	proto.RegisterType((*MsgToggleDelegatorWhitelistSwitch)(nil), "stafihub.stafihub.rstaking.MsgToggleDelegatorWhitelistSwitch")
	proto.RegisterType((*MsgToggleDelegatorWhitelistSwitchResponse)(nil), "stafihub.stafihub.rstaking.MsgToggleDelegatorWhitelistSwitchResponse")
}

func init() { proto.RegisterFile("rstaking/tx.proto", fileDescriptor_dc4bfb0e643e29ba) }

var fileDescriptor_dc4bfb0e643e29ba = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6b, 0x13, 0x4f,
	0x18, 0xcf, 0xfe, 0x0b, 0xf9, 0xdb, 0xa7, 0x08, 0x76, 0xad, 0x18, 0xd7, 0x3a, 0xd5, 0x45, 0xac,
	0x22, 0x9d, 0xb1, 0x15, 0xd4, 0x4b, 0x85, 0x46, 0x45, 0x7a, 0x08, 0x48, 0x1a, 0x52, 0xf0, 0x36,
	0xd9, 0x9d, 0x4e, 0x86, 0x6e, 0x76, 0xc2, 0xce, 0xf4, 0x45, 0x10, 0x3c, 0x79, 0xd7, 0x2f, 0x21,
	0xf8, 0x4d, 0x7a, 0xcc, 0x51, 0x3c, 0x14, 0x49, 0xbe, 0x88, 0x6c, 0x36, 0x3b, 0x89, 0x66, 0x37,
	0x9b, 0xd6, 0x53, 0x26, 0xb3, 0xcf, 0xef, 0x65, 0xe6, 0x37, 0xcf, 0x0c, 0x2c, 0x47, 0x4a, 0xd3,
	0x43, 0x11, 0x72, 0xa2, 0x4f, 0x71, 0x37, 0x92, 0x5a, 0xda, 0x8e, 0xd2, 0xf4, 0x40, 0xb4, 0x8f,
	0x5a, 0xd8, 0x0c, 0xd2, 0x22, 0x67, 0x85, 0x4b, 0x2e, 0x87, 0x65, 0x24, 0x1e, 0x25, 0x08, 0x07,
	0x79, 0x52, 0x75, 0xa4, 0x22, 0x2d, 0xaa, 0x18, 0x39, 0xde, 0x6c, 0x31, 0x4d, 0x37, 0x89, 0x27,
	0x45, 0x98, 0x7c, 0x77, 0x3f, 0x5b, 0x70, 0xbd, 0xa6, 0xf8, 0x1e, 0xd3, 0xbb, 0xe1, 0x41, 0x40,
	0xb5, 0x90, 0x61, 0x95, 0x2a, 0x66, 0x57, 0xe0, 0x7f, 0x2f, 0x62, 0x54, 0xcb, 0xa8, 0x62, 0xdd,
	0xb5, 0x1e, 0x2e, 0xd6, 0xd3, 0xbf, 0x76, 0x03, 0xae, 0x8a, 0xc9, 0xd2, 0xca, 0x7f, 0xf1, 0xf7,
	0x2a, 0x3e, 0x3b, 0x5f, 0x2b, 0xfd, 0x3c, 0x5f, 0x7b, 0xc0, 0x85, 0x8e, 0x7d, 0x79, 0xb2, 0x43,
	0x46, 0xda, 0xc9, 0xcf, 0x86, 0xf2, 0x0f, 0x89, 0xfe, 0xd0, 0x65, 0x0a, 0xef, 0x86, 0xba, 0xfe,
	0x27, 0x89, 0x7b, 0x07, 0x6e, 0x67, 0xd8, 0xa8, 0x33, 0xd5, 0x95, 0xa1, 0x62, 0xee, 0x3b, 0x58,
	0xa9, 0x29, 0xbe, 0xe3, 0xfb, 0x4d, 0x1a, 0x34, 0xe4, 0x7e, 0x5b, 0x68, 0x16, 0x08, 0xa5, 0x67,
	0xd8, 0x44, 0x00, 0xc7, 0x34, 0xd8, 0xf1, 0xfd, 0x88, 0x29, 0x95, 0x78, 0xac, 0x4f, 0xcc, 0xb8,
	0x08, 0x56, 0xb3, 0x18, 0x8d, 0xe2, 0x36, 0xdc, 0xab, 0x29, 0xde, 0x90, 0x9c, 0x07, 0xac, 0x49,
	0x03, 0xe1, 0xc7, 0xac, 0xa6, 0x6c, 0xef, 0x44, 0x68, 0xaf, 0x9d, 0x2f, 0xef, 0x3e, 0x86, 0x47,
	0x85, 0x70, 0xa3, 0xf5, 0xdd, 0x82, 0xa5, 0x9a, 0xe2, 0xfb, 0x42, 0xb7, 0xfd, 0x88, 0x9e, 0xcc,
	0x58, 0x55, 0x0b, 0xca, 0xb4, 0x23, 0x8f, 0x42, 0x3d, 0x5c, 0xd1, 0xd2, 0xd6, 0x2d, 0x9c, 0x6c,
	0x2e, 0x8e, 0xf3, 0xc5, 0xa3, 0x7c, 0xf1, 0x2b, 0x29, 0xc2, 0x2a, 0x19, 0x05, 0xb2, 0x3e, 0x47,
	0x20, 0x31, 0xa0, 0x3e, 0x62, 0xb6, 0x57, 0x61, 0x31, 0x62, 0x9e, 0xe8, 0x0a, 0x16, 0xea, 0xca,
	0xc2, 0x50, 0x7f, 0x3c, 0xe1, 0xde, 0x18, 0x9e, 0x97, 0xd4, 0xaa, 0x59, 0x42, 0x13, 0x9c, 0x64,
	0x3b, 0x5f, 0xb3, 0x80, 0xf1, 0xd8, 0xeb, 0xdc, 0x31, 0xf9, 0xec, 0xef, 0x98, 0xc6, 0x33, 0xee,
	0x7d, 0x70, 0xf3, 0x79, 0x33, 0xc3, 0x32, 0x85, 0x97, 0x0b, 0x2b, 0x0f, 0x9e, 0x6a, 0x6d, 0xf5,
	0xca, 0xb0, 0x50, 0x53, 0xdc, 0xfe, 0x08, 0xd7, 0xa6, 0xba, 0x86, 0xe0, 0xfc, 0x06, 0xc5, 0x19,
	0xe7, 0xdb, 0x79, 0x7e, 0x41, 0x40, 0xea, 0xc2, 0xfe, 0x04, 0xcb, 0xd3, 0xdd, 0xf0, 0xa4, 0x80,
	0x6d, 0x0a, 0xe1, 0xbc, 0xb8, 0x28, 0xc2, 0x18, 0xf8, 0x66, 0x01, 0x2a, 0xe8, 0x8e, 0xed, 0x02,
	0xf2, 0xd9, 0x70, 0xe7, 0xcd, 0x3f, 0xc1, 0x8d, 0x51, 0x1f, 0xae, 0x98, 0xc6, 0x5a, 0x2f, 0xa0,
	0x4c, 0x0b, 0x1d, 0x32, 0x67, 0xa1, 0x51, 0xf9, 0x6a, 0xc1, 0xcd, 0xbc, 0xd3, 0xff, 0xac, 0x78,
	0x93, 0xb3, 0x70, 0xce, 0xcb, 0xcb, 0xe1, 0x32, 0x22, 0xca, 0xed, 0x89, 0xf9, 0x22, 0xca, 0x83,
	0xcf, 0x19, 0x51, 0x51, 0x4b, 0x55, 0xdf, 0x9e, 0xf5, 0x91, 0xd5, 0xeb, 0x23, 0xeb, 0x57, 0x1f,
	0x59, 0x5f, 0x06, 0xa8, 0xd4, 0x1b, 0xa0, 0xd2, 0x8f, 0x01, 0x2a, 0xbd, 0xdf, 0x98, 0xb8, 0xbc,
	0x52, 0x85, 0xf1, 0xe0, 0x94, 0x8c, 0x9f, 0xc8, 0xf8, 0x1e, 0x6b, 0x95, 0x87, 0x8f, 0xda, 0xd3,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xfe, 0xdc, 0xc7, 0x3b, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetInflationBase(ctx context.Context, in *MsgSetInflationBase, opts ...grpc.CallOption) (*MsgSetInflationBaseResponse, error)
	AddValToWhitelist(ctx context.Context, in *MsgAddValToWhitelist, opts ...grpc.CallOption) (*MsgAddValToWhitelistResponse, error)
	ToggleValidatorWhitelistSwitch(ctx context.Context, in *MsgToggleValidatorWhitelistSwitch, opts ...grpc.CallOption) (*MsgToggleValidatorWhitelistSwitchResponse, error)
	Withdraw(ctx context.Context, in *MsgWithdraw, opts ...grpc.CallOption) (*MsgWithdrawResponse, error)
	AddDelegatorToWhitelist(ctx context.Context, in *MsgAddDelegatorToWhitelist, opts ...grpc.CallOption) (*MsgAddDelegatorToWhitelistResponse, error)
	ToggleDelegatorWhitelistSwitch(ctx context.Context, in *MsgToggleDelegatorWhitelistSwitch, opts ...grpc.CallOption) (*MsgToggleDelegatorWhitelistSwitchResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetInflationBase(ctx context.Context, in *MsgSetInflationBase, opts ...grpc.CallOption) (*MsgSetInflationBaseResponse, error) {
	out := new(MsgSetInflationBaseResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rstaking.Msg/SetInflationBase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddValToWhitelist(ctx context.Context, in *MsgAddValToWhitelist, opts ...grpc.CallOption) (*MsgAddValToWhitelistResponse, error) {
	out := new(MsgAddValToWhitelistResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rstaking.Msg/AddValToWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ToggleValidatorWhitelistSwitch(ctx context.Context, in *MsgToggleValidatorWhitelistSwitch, opts ...grpc.CallOption) (*MsgToggleValidatorWhitelistSwitchResponse, error) {
	out := new(MsgToggleValidatorWhitelistSwitchResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rstaking.Msg/ToggleValidatorWhitelistSwitch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Withdraw(ctx context.Context, in *MsgWithdraw, opts ...grpc.CallOption) (*MsgWithdrawResponse, error) {
	out := new(MsgWithdrawResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rstaking.Msg/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddDelegatorToWhitelist(ctx context.Context, in *MsgAddDelegatorToWhitelist, opts ...grpc.CallOption) (*MsgAddDelegatorToWhitelistResponse, error) {
	out := new(MsgAddDelegatorToWhitelistResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rstaking.Msg/AddDelegatorToWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ToggleDelegatorWhitelistSwitch(ctx context.Context, in *MsgToggleDelegatorWhitelistSwitch, opts ...grpc.CallOption) (*MsgToggleDelegatorWhitelistSwitchResponse, error) {
	out := new(MsgToggleDelegatorWhitelistSwitchResponse)
	err := c.cc.Invoke(ctx, "/stafihub.stafihub.rstaking.Msg/ToggleDelegatorWhitelistSwitch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetInflationBase(context.Context, *MsgSetInflationBase) (*MsgSetInflationBaseResponse, error)
	AddValToWhitelist(context.Context, *MsgAddValToWhitelist) (*MsgAddValToWhitelistResponse, error)
	ToggleValidatorWhitelistSwitch(context.Context, *MsgToggleValidatorWhitelistSwitch) (*MsgToggleValidatorWhitelistSwitchResponse, error)
	Withdraw(context.Context, *MsgWithdraw) (*MsgWithdrawResponse, error)
	AddDelegatorToWhitelist(context.Context, *MsgAddDelegatorToWhitelist) (*MsgAddDelegatorToWhitelistResponse, error)
	ToggleDelegatorWhitelistSwitch(context.Context, *MsgToggleDelegatorWhitelistSwitch) (*MsgToggleDelegatorWhitelistSwitchResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetInflationBase(ctx context.Context, req *MsgSetInflationBase) (*MsgSetInflationBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInflationBase not implemented")
}
func (*UnimplementedMsgServer) AddValToWhitelist(ctx context.Context, req *MsgAddValToWhitelist) (*MsgAddValToWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddValToWhitelist not implemented")
}
func (*UnimplementedMsgServer) ToggleValidatorWhitelistSwitch(ctx context.Context, req *MsgToggleValidatorWhitelistSwitch) (*MsgToggleValidatorWhitelistSwitchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleValidatorWhitelistSwitch not implemented")
}
func (*UnimplementedMsgServer) Withdraw(ctx context.Context, req *MsgWithdraw) (*MsgWithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (*UnimplementedMsgServer) AddDelegatorToWhitelist(ctx context.Context, req *MsgAddDelegatorToWhitelist) (*MsgAddDelegatorToWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDelegatorToWhitelist not implemented")
}
func (*UnimplementedMsgServer) ToggleDelegatorWhitelistSwitch(ctx context.Context, req *MsgToggleDelegatorWhitelistSwitch) (*MsgToggleDelegatorWhitelistSwitchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleDelegatorWhitelistSwitch not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetInflationBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetInflationBase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetInflationBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rstaking.Msg/SetInflationBase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetInflationBase(ctx, req.(*MsgSetInflationBase))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddValToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddValToWhitelist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddValToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rstaking.Msg/AddValToWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddValToWhitelist(ctx, req.(*MsgAddValToWhitelist))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ToggleValidatorWhitelistSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgToggleValidatorWhitelistSwitch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ToggleValidatorWhitelistSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rstaking.Msg/ToggleValidatorWhitelistSwitch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ToggleValidatorWhitelistSwitch(ctx, req.(*MsgToggleValidatorWhitelistSwitch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdraw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rstaking.Msg/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Withdraw(ctx, req.(*MsgWithdraw))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddDelegatorToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddDelegatorToWhitelist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddDelegatorToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rstaking.Msg/AddDelegatorToWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddDelegatorToWhitelist(ctx, req.(*MsgAddDelegatorToWhitelist))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ToggleDelegatorWhitelistSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgToggleDelegatorWhitelistSwitch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ToggleDelegatorWhitelistSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stafihub.stafihub.rstaking.Msg/ToggleDelegatorWhitelistSwitch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ToggleDelegatorWhitelistSwitch(ctx, req.(*MsgToggleDelegatorWhitelistSwitch))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stafihub.stafihub.rstaking.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetInflationBase",
			Handler:    _Msg_SetInflationBase_Handler,
		},
		{
			MethodName: "AddValToWhitelist",
			Handler:    _Msg_AddValToWhitelist_Handler,
		},
		{
			MethodName: "ToggleValidatorWhitelistSwitch",
			Handler:    _Msg_ToggleValidatorWhitelistSwitch_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _Msg_Withdraw_Handler,
		},
		{
			MethodName: "AddDelegatorToWhitelist",
			Handler:    _Msg_AddDelegatorToWhitelist_Handler,
		},
		{
			MethodName: "ToggleDelegatorWhitelistSwitch",
			Handler:    _Msg_ToggleDelegatorWhitelistSwitch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rstaking/tx.proto",
}

func (m *MsgSetInflationBase) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetInflationBase) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetInflationBase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.InflationBase.Size()
		i -= size
		if _, err := m.InflationBase.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetInflationBaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetInflationBaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetInflationBaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddValToWhitelist) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddValToWhitelist) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddValToWhitelist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddValToWhitelistResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddValToWhitelistResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddValToWhitelistResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgToggleValidatorWhitelistSwitch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgToggleValidatorWhitelistSwitch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgToggleValidatorWhitelistSwitch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgToggleValidatorWhitelistSwitchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgToggleValidatorWhitelistSwitchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgToggleValidatorWhitelistSwitchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdraw) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdraw) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdraw) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddDelegatorToWhitelist) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddDelegatorToWhitelist) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddDelegatorToWhitelist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DelAddress) > 0 {
		i -= len(m.DelAddress)
		copy(dAtA[i:], m.DelAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DelAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddDelegatorToWhitelistResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddDelegatorToWhitelistResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddDelegatorToWhitelistResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgToggleDelegatorWhitelistSwitch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgToggleDelegatorWhitelistSwitch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgToggleDelegatorWhitelistSwitch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgToggleDelegatorWhitelistSwitchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgToggleDelegatorWhitelistSwitchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgToggleDelegatorWhitelistSwitchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetInflationBase) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.InflationBase.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSetInflationBaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddValToWhitelist) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddValToWhitelistResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgToggleValidatorWhitelistSwitch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgToggleValidatorWhitelistSwitchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdraw) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddDelegatorToWhitelist) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DelAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddDelegatorToWhitelistResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgToggleDelegatorWhitelistSwitch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgToggleDelegatorWhitelistSwitchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetInflationBase) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetInflationBase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetInflationBase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationBase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InflationBase.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetInflationBaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetInflationBaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetInflationBaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddValToWhitelist) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddValToWhitelist: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddValToWhitelist: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddValToWhitelistResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddValToWhitelistResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddValToWhitelistResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgToggleValidatorWhitelistSwitch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgToggleValidatorWhitelistSwitch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgToggleValidatorWhitelistSwitch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgToggleValidatorWhitelistSwitchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgToggleValidatorWhitelistSwitchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgToggleValidatorWhitelistSwitchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdraw) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdraw: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdraw: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddDelegatorToWhitelist) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddDelegatorToWhitelist: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddDelegatorToWhitelist: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddDelegatorToWhitelistResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddDelegatorToWhitelistResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddDelegatorToWhitelistResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgToggleDelegatorWhitelistSwitch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgToggleDelegatorWhitelistSwitch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgToggleDelegatorWhitelistSwitch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgToggleDelegatorWhitelistSwitchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgToggleDelegatorWhitelistSwitchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgToggleDelegatorWhitelistSwitchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
